version: 0.0

os: linux
files:
  - source: /
    destination: /var/www/html/
    overwrite: true
permissions:
  - object: /var/www
    pattern: "html"
    owner: ec2-user
    group: ec2-user
    type:
      - directory
  - object: /var/www/html
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 444
    type:
      - file
hooks:
  ApplicationStart:
    - location: deploy_script.sh
