version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
    # - some command
  pre_build: # ビルド実行前に実行する処理等の設定
    commands:
      - cd frontend
      - npm i
  build: # ビルド実行処理等の設定
    commands:
      - npm run build
      - cp ../appspec.yml dist/ # appspec.yml を dist ディレクトリにコピー
  post_build:
    commands:
      - aws deploy push --application-name morisaki-for-ec2 --s3-location s3://morisaki-for-deploy-of-ec2/artifact.zip --source dist
artifacts:
  files: # 出力するビルドファイル
    - "**/*"
  base-directory: "frontend/dist"
