version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
      java: corretto17
    commands:
    # - some command
  pre_build: # ビルド実行前に実行する処理等の設定
    commands:
      - chmod +x deploy_script.sh
      - cd frontend
      - npm i
  build: # ビルド実行処理等の設定
    commands:
      - npm run build
      - mkdir -p ../backend/src/main/resources/public
      - cp ./dist/* ../backend/src/main/resources/public
      - cd ../backend
      - chmod +x ./gradlew
      - ./gradlew build
      - mkdir -p ../build
      - cp build/libs/flower-0.0.1-SNAPSHOT.jar ../build
      - cp ../appspec.yml ../build
      - cp ../deploy_script.sh ../build
      - cp src/main/resources/public/ ../build
      - cd ..
  post_build:
    commands:
      - aws deploy push --application-name morisaki-for-ec2 --s3-location s3://morisaki-for-deploy-of-ec2/artifact.zip --source build
artifacts:
  files: # 出力するビルドファイル
    - "**/*"
  base-directory: build
