version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
      java: corretto17
    commands:
    # - some command
  pre_build: # ビルド実行前に実行する処理等の設定
    commands:
      - chmod +x deploy_script.sh
      - cd frontend
      - npm i
  build: # ビルド実行処理等の設定
    commands:
      - npm run build
      - cp ../appspec.yml dist/ # appspec.yml を dist ディレクトリにコピー
      - cp ../deploy_script.sh dist/
      - cd ..
      - cd backend
      - chmod +x ./gradlew
      - ./gradlew build
      - cp build/libs/flower-0.0.1-SNAPSHOT.jar ../frontend/dist
      - cd ..
      - cd frontend
  post_build:
    commands:
      - aws deploy push --application-name morisaki-for-ec2 --s3-location s3://morisaki-for-deploy-of-ec2/artifact.zip --source dist
artifacts:
  files: # 出力するビルドファイル
    - "**/*"
  base-directory: frontend/dist
