version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
      java: corretto17
    commands:
      - cd frontend
      - npm i
  pre_build:
    commands:
      - npm run build
      - mkdir -p ../backend/src/main/resources/public
      - cp ./dist/* ../backend/src/main/resources/public
      - cd ../backend
      - ./gradlew build
      - mkdir -p ../build
      - cp build/libs/flower-0.0.1-SNAPSHOT.jar ../build
      - cp ../appspec.yml ../build
      - cd ..
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 398649269234.dkr.ecr.ap-northeast-1.amazonaws.com
      - REPOSITORY_URI=398649269234.dkr.ecr.ap-northeast-1.amazonaws.com/morisaki-ecr
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - printf '{"Version":"1.0","ImageURI":"%s"}' $REPOSITORY_URI:$IMAGE_TAG > imageDetail.json
artifacts:
  files: imageDetail.json
