spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://morisaki-rds.ctxc0xamayvr.ap-northeast-1.rds.amazonaws.com/flower_shop
#    url: jdbc:postgresql://localhost:5431/flower_shop
    username: flower
#    username: user
    password: iehoy117
#    password: flower
  jpa:
    show-sql: true
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
